### ISSUE TITLE
Feature request: Polyphony mode on level cv's

### ISSUE THREAD

**Issue by gwatcha** [gluethegiant/gtg-rack#7] opened 2020-06-15 23:55 UTC
For the bus's with polyponic input audio, it would be useful to allow for polyphonic cv to control the level for each voice, as opposed to all the voices with a monophonic input.

**Comment by gluethegiant** [comment] 2020-07-14 13:47
Each of the level CVs control a stereo level output (to a stereo bus) by design. In other words, they are output levels only. An input level CV on Metro City Bus could be added with polyphonic level capability to do what you are requesting, however. Metro City Bus has some extra polyphonic capabilities with it's panning spread modes.

I wonder if a very simple strip with one polyphonic in, one polyphonic out, and 16 levels for each polyphonic channel with CVs is available (or could be created) to put right before a Metro City Bus Mixer.

**Comment by gluethegiant** [comment] 2021-01-25 15:59
Since level CVs are for stereo outputs, I'm closing this issue.

**Closed as completed by gluethegiant** 2021-01-25 15:59 UTC
Labels: enhancement
